# site settings
title: Alan Bakhri
author: Alan Bakhri
description: My personal website and info about me

github: alanbakhri
twitter: alanbakhry

brand:
  name: Portfolio
  path: /images

url: ""
baseurl: ""

# build settings
markdown: kramdown
highlighter: pygments

gems:
  - jekyll-feed
