title: Alan Bakhri
author:
  name: Alan Bakhri
  github: alanbakhri
  twitter: alanbakhry
  youtube: alanbakhri
  avatar: avatar.png

brand:
  name: Portfolio
  path: /images

description: My personal website and info about me

url: ""
baseurl: ""

markdown: kramdown
highlighter: pygments

gems:
  - jekyll-feed

gem:
